# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'ProjectSDK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '5.8.1'	
  pod 'LibrarySDK', :path => '../LibrarySDK'

  target 'ProjectSDKTests' do
    inherit! :search_paths
    pod 'LibrarySDK', :path => '../LibrarySDK'
  end

  target 'ProjectSDKUITests' do
  end

end

